name: reconcile_on_demand
on: [pull_request, push, workflow_dispatch]
jobs:
  reconcile_on_demand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: poetry install
      - run: poetry run python reconcile/main.py --help
      - run: poetry run python reconcile/main.py fetch-data
      - run: poetry run python reconcile/main.py parse-data
      - run: poetry run python reconcile/main.py create-db
      - run: poetry run python reconcile/main.py all-reports
